liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size:       [800,230]
                    mode :      outbound
                    allow_upscale: true

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
